export const AuditActionType = {
    LOCK_DEVICE: "LOCK_DEVICE",
    UNLOCK_DEVICE: "UNLOCK_DEVICE",
    UPDATE_SCREEN_TIME: "UPDATE_SCREEN_TIME",
    APPROVE_REQUEST: "APPROVE_REQUEST",
    REJECT_REQUEST: "REJECT_REQUEST",
};