export const AuditActionType = {
  LOCK_DEVICE: "LOCK_DEVICE",
  UNLOCK_DEVICE: "UNLOCK_DEVICE",
  APPROVE_REQUEST: "APPROVE_REQUEST",
  REJECT_REQUEST: "REJECT_REQUEST",
  CREATE_REQUEST: "CREATE_REQUEST"
};