export const NotificationType = {

  // Requests
  EXTENSION_REQUEST_CREATED: "EXTENSION_REQUEST_CREATED",
  EXTENSION_REQUEST_APPROVED: "EXTENSION_REQUEST_APPROVED",
  EXTENSION_REQUEST_REJECTED: "EXTENSION_REQUEST_REJECTED",

  // Device
  DEVICE_LOCKED: "DEVICE_LOCKED",
  DEVICE_UNLOCKED: "DEVICE_UNLOCKED",

  // Screen Time
  SCREEN_TIME_ENDING: "SCREEN_TIME_ENDING",
  SCREEN_TIME_ENDED: "SCREEN_TIME_ENDED",
  SCREEN_TIME_UPDATED: "SCREEN_TIME_UPDATED",

  // Safety
  SOS_TRIGGERED: "SOS_TRIGGERED",
  BYPASS_ATTEMPT: "BYPASS_ATTEMPT",
  SUSPICIOUS_APP_ACTIVITY: "SUSPICIOUS_APP_ACTIVITY",

  // Apps
  NEW_APP_INSTALLED: "NEW_APP_INSTALLED"
};