export const NotificationType = {

// Child Connection
CHILD_LOGGED_IN: "CHILD_LOGGED_IN",   
CHILD_DISCONNECTED: "CHILD_DISCONNECTED",

// Child Management
CHILD_ADDED: "CHILD_ADDED",
CHILD_PROFILE_UPDATED: "CHILD_PROFILE_UPDATED",
CHILD_DELETED: "CHILD_DELETED",

// Child Location
CHILD_LOCATION_UPDATED: "CHILD_LOCATION_UPDATED",

  // Requests
  EXTENSION_REQUEST_CREATED: "EXTENSION_REQUEST_CREATED",
  EXTENSION_REQUEST_APPROVED: "EXTENSION_REQUEST_APPROVED",
  EXTENSION_REQUEST_REJECTED: "EXTENSION_REQUEST_REJECTED",

  // Device
  DEVICE_LOCKED: "DEVICE_LOCKED",
  DEVICE_UNLOCKED: "DEVICE_UNLOCKED",
  DEVICE_ADDED: "DEVICE_ADDED",
  DEVICE_DELETED: "DEVICE_DELETED",
  DEVICE_RENAMED: "DEVICE_RENAMED",

  // Screen Time
  SCREEN_TIME_ENDING: "SCREEN_TIME_ENDING",
  SCREEN_TIME_ENDED: "SCREEN_TIME_ENDED",
  SCREEN_TIME_UPDATED: "SCREEN_TIME_UPDATED",

  // Safety
  SOS_TRIGGERED: "SOS_TRIGGERED",
  BYPASS_ATTEMPT: "BYPASS_ATTEMPT",
  SUSPICIOUS_APP_ACTIVITY: "SUSPICIOUS_APP_ACTIVITY",
  LOCATION_UPDATE: "LOCATION_UPDATE",

  // Apps
  NEW_APP_INSTALLED: "NEW_APP_INSTALLED"
};