export const NotificationType = {
  EXTENSION_REQUEST_CREATED: "EXTENSION_REQUEST_CREATED",
  EXTENSION_REQUEST_APPROVED: "EXTENSION_REQUEST_APPROVED",
  EXTENSION_REQUEST_REJECTED: "EXTENSION_REQUEST_REJECTED",
  DEVICE_LOCKED: "DEVICE_LOCKED",
  DEVICE_UNLOCKED: "DEVICE_UNLOCKED",
  SCREEN_TIME_ENDING: "SCREEN_TIME_ENDING",
  SOS_TRIGGERED: "SOS_TRIGGERED"
};