export const RecommendationCode = {
    REVIEW_DAILY_LIMIT: "REVIEW_DAILY_LIMIT",
    PENDING_REQUESTS: "PENDING_REQUESTS",
    SET_DAILY_LIMIT: "SET_DAILY_LIMIT",
    CHECK_LOCK_REASON: "CHECK_LOCK_REASON",
    YOUNG_CHILD_GUIDANCE: "YOUNG_CHILD_GUIDANCE",
    HIGH_DAILY_USAGE: "HIGH_DAILY_USAGE",
    SET_WEEKLY_SCHEDULE: "SET_WEEKLY_SCHEDULE",
    ENABLE_LIMIT: "ENABLE_LIMIT",
    SUGGEST_ACTIVITY: "SUGGEST_ACTIVITY"

};

export const RecommendationPriority = {
    HIGH: "HIGH",
    MEDIUM: "MEDIUM",
    LOW: "LOW"
};