export const icons = {
  settings: require("../../assets/icons/settings.png"),
  accessibility: require("../../assets/icons/accessibility.png"),
  points: require("../../assets/icons/points.png"),
  level: require("../../assets/icons/level.png"),
  coins: require("../../assets/icons/coins.png"),
  time: require("../../assets/icons/time.png"),
  apps: require("../../assets/icons/apps.png"),
  extend: require("../../assets/icons/extend.png"),
  shop: require("../../assets/icons/shop.png"),
  tasks: require("../../assets/icons/tasks.png"),
  achievements: require("../../assets/icons/achievements.png"),
  goals: require("../../assets/icons/goals.png"),
  heart: require("../../assets/icons/heart.png"),
  bulb: require("../../assets/icons/bulb.png"),
  help: require("../../assets/icons/help.png"),
  panic: require("../../assets/icons/panic.png"),
  back: require("../../assets/icons/back.png"),
  hamburger: require("../../assets/icons/hamburger.png"),
};
