export const JOIN_PARENT = "JOIN_PARENT";
export const JOIN_CHILD = "JOIN_CHILD";
export const REQUEST_REFRESH_FROM_PARENT = "REQUEST_REFRESH_FROM_PARENT";
export const REQUEST_CHILD_LOCATION = "REQUEST_CHILD_LOCATION";
export const LOCATION_LIVE_UPDATE = "LOCATION_LIVE_UPDATE";
export const PARENT_LOGOUT = "PARENT_LOGOUT";
export const FORCE_CHILD_LOGOUT = "FORCE_CHILD_LOGOUT";
export const DELETE_DEVICE = "DELETE_DEVICE";

// Notifications
export const NOTIFICATION_CREATED = "NOTIFICATION_CREATED";