/** Palette for child avatars */
export const CHILD_ACCENT_COLOR_1 = "#18C29C";
export const CHILD_ACCENT_COLOR_2 = "#7B9CFF";
export const CHILD_ACCENT_COLOR_3 = "#D46AD8";
export const CHILD_ACCENT_COLOR_4 = "#FF9F43";
export const CHILD_ACCENT_COLOR_5 = "#54A0FF";
export const CHILD_ACCENT_COLOR_6 = "#EE5A6F";
export const CHILD_ACCENT_COLOR_7 = "#00D2D3";
export const CHILD_ACCENT_COLOR_8 = "#FECA57";
export const CHILD_ACCENT_COLOR_9 = "#5F27CD";
export const CHILD_ACCENT_COLOR_10 = "#10AC84";

export const CHILD_ACCENT_COLORS = [
  CHILD_ACCENT_COLOR_1,
  CHILD_ACCENT_COLOR_2,
  CHILD_ACCENT_COLOR_3,
  CHILD_ACCENT_COLOR_4,
  CHILD_ACCENT_COLOR_5,
  CHILD_ACCENT_COLOR_6,
  CHILD_ACCENT_COLOR_7,
  CHILD_ACCENT_COLOR_8,
  CHILD_ACCENT_COLOR_9,
  CHILD_ACCENT_COLOR_10,
];